version: "3.9"

services:
  app:
    build: .
    container_name: graph-next-node-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=test_graphql
      - JWT_SECRET=ec7d0d2b3686ae44aeb33a68fba008331bb2547be584c1b975e209701e59363d019980d8a1f6dc4b97eaa2dd6d19f0b20d6f514281b2ef47f59261f8548c0fd3
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
